# Generated by Django 5.2.5 on 2025-08-23 08:33

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128, unique=True)),
                ('width', models.PositiveIntegerField(help_text='Width in pixels')),
                ('height', models.PositiveIntegerField(help_text='Height in pixels')),
                ('size', models.PositiveIntegerField(help_text='Size in bytes', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1000000000)])),
                ('color', models.CharField(max_length=20)),
                ('format', models.CharField(max_length=5)),
                ('image', models.ImageField(upload_to='generated/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
