# Generated by Django 5.2.5 on 2025-08-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_generatedimage_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='filename',
        ),
    ]
